name: LifeLongLearner
favicon: null
layout_spectrum: 0.9291686727665365
typography_spectrum: 0.35624
title: Life Long Learner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#fefefe'
    - '#0a5499'
    - '#faab81'
    - '#c96232'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
