name: LifeLongLearner
favicon: null
layout_spectrum: 0.9291686727665365
typography_spectrum: 0.6357936775311828
title: Life Long Learner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.012537084519863129
  lightness: 0.09166565234772861
  saturation: 0.8983774303924292
  rhythmicContrast: 0.05869380896911025
purpose: []
